### ISSUE TITLE
Why doesn't it support mifare plus?

### ISSUE THREAD

**Issue by darkalexpp** [nfc-tools/libfreefare#117]
Why doesn't it support mifare plus?
SAK = 20

**Comment by darconeous** [comment]
Because no one who has all of the information required to implement it has taken the time to implement it.

A complicating factor is that the MIFARE Plus datasheet is confidential and only available under NDA, which further limits the pool of people who might otherwise be willing to implement it.

**Comment by smortex** [comment]
The information is available here if someone wants to add support (I am not under NDA so can redistribute it, and so you do unless you signed an NDA):
https://marvin.blogreen.org/~romain/nfc/Mifare%20Plus.pdf
