### ISSUE TITLE
Just some explanation needed

### ISSUE THREAD

**Issue by alenloncaric** [nfc-tools/libfreefare#139]
Guys first of all GREAT project!

I have a mifare classic 1k card. I checked what mifare is sending for authentication and it sends (FOR KEY A) sector 0:
60 00 FF FF FF FF FF FF 04 94 84 B3

when checking other forum threads they are sending this
FF 86 00 00 05 01 00 00 60 00

Why is this different ? Does mifare classic have different command sets ?

**Comment by doegox** [comment]
60 00 FF FF FF FF FF FF 04 94 84 B3 is the syntax of a command sent to a PN53x chip to tell it to perform a MIFARE Classic authentication.

FF 86 00 00 05 01 00 00 60 00 is the syntax of a command sent to an ACR122U reader to tell it to perform a MIFARE Classic authentication (based on keys already uploaded into the reader).

Real MIFARE Classic authentication is a proprietary protocol performed in several steps by the firmware of the PN53x or of the ACR122U.
