### ISSUE TITLE
Some functions in mifare_classic.c apparently don't check input data

### ISSUE THREAD

**Issue by GoogleCodeExporter** [nfc-tools/libfreefare#23]
```
Most functions in mifare_classic.c contain a little prelude to check the input 
data for sanity:

    ASSERT_ACTIVE (tag);
    ASSERT_MIFARE_CLASSIC (tag);

Some other functions don't do this. I found that at least the following 
functions don't check the state of tag:

    mifare_classic_get_trailer_block_permission
    mifare_classic_get_data_block_permission
    mifare_classic_format_sector

Perhaps I am in err about this, but if the libfreefare really does not perform 
any checks here, this might be a bug. Perhaps the problem also affects other 
tag types.

```

Original issue reported on code.google.com by `fuz...@gmail.com` on 18 Mar 2014 at 1:59

**Comment by smortex** [comment]
The `ASSERT_*` macros are only present for methods that make the PCD perform an operations on a PICC (with `CLASSIC_TRANSCEIVE`)…  let's call them _low level methods_.

We also provide methods to make it easy to perform some operations, e.g. `mifare_classic_format_sector()` which does not directly bind to an operation that the PICC can handle directly. Instead, the library will issue various calls to the low-level methods to achive its goal.  Each low-level method will ensure that the context is okay, so there is no point in also checking this at the high API level.
