### ISSUE TITLE
mifare_desfire_read_data() reads behind end of buffer

### ISSUE THREAD

**Issue by GoogleCodeExporter** [nfc-tools/libfreefare#28]
The internal function `read_data()` in mifare_desfire.c contains the following comment:

```c
    /*
     * FIXME: This is bogus: the user has to provide a data buffer with enougth
     * room to store CRC + padding or MAC.  If the user wants to read 1 byte,
     * there is no reason to provide a 16 bytes buffer.
     */
```

It is absolutely inacceptable that read_data() reads bytes from data beyond length. Please either document how long the buffer behind data has to be or rework the function to write at most length bytes into data. As is, this is a huge security hole and makes writing a library wrapper extremely difficult as I cannot make any assumptions about extra memory I must allocate beyond what is documented. Please fix this issue ASAP.

Original issue reported on code.google.com by `fuz...@gmail.com` on 9 Apr 2014 at 6:24

**Comment by smortex** [comment]
> The submitted fix is actually not sufficient for reading a Record File as a whole when no size is specified.
>
> Assign to me as I have started something last week but failed to update this entry.

This was fixed a long time ago in a0ba196b498979921b9a9247771b816bbfec014f.
