### ISSUE TITLE
Problems with Big Endian architectures

### ISSUE THREAD

**Issue by lpouzenc** [nfc-tools/libfreefare#39]
Hi,

I dig into libfreefare for the PCSC integration, and it seems that the lib will have troubles on machines with big-endian architectures. I'm lacking of real hardware to test extensively this affirmation.

Definition of le24toh() is clearly not BE-aware and it's used to decode Mifaire DESFire file size.

Regards,
Ludovic

**Comment by smortex** [comment]
This code…

~~~c
uint32_t x = 1234;
~~~

…stores 1234 in `x`, regardless of the architecture. 1234 == 1 × 10⁴ + 2 × 10³ + 3 × 10² + 4 × 10⁰ on all platforms, big or little-endian… so everything is fine!

This `le24toh()` basically function does this and is inspired by *Write Portable Code* by *Brian Hook*.
