### ISSUE TITLE
Library doesn't compile with --enable-debug

### ISSUE THREAD

**Issue by jekkos** [nfc-tools/libfreefare#43]
Looks like there was something forgotten in felica.c:47, felica_transceive

    DEBUG_XFER (data_in, data_in_length, "===> ");

data_in_length is not passed as an argument and thus unknown to the compiler when enabling WITH_DEBUG. I changed this to sizeof (data_in) and now all works well.

**Comment by smortex** [comment]
Fixed, thanks!
