### ISSUE TITLE
When is new release comming?

### ISSUE THREAD

**Issue by masterkorp** [nfc-tools/libfreefare#45]
Hello,

The [lastest release](https://github.com/nfc-tools/libfreefare/releases/tag/libfreefare-0.4.0) was on 4th, December, 2013. Do you guys plan on publishing another release?

Regards,
Alfredo Palhares

**Comment by smortex** [comment]
Hello,

The library development takes place in developers spare time (until one of us has to to real work that needs some hacking).  You are however free to contribute, and we will be happy to guide you and merge your pull requests.

Milestone 1.0.0 was created if you are looking for blockers for a new release, and any patches for other open issues would be greatly appreciated!
