### ISSUE TITLE
Bunch of issues from the Go wrapper

### ISSUE THREAD

**Issue by fuzxxl** [nfc-tools/libfreefare#47]
The following issues were found by me when I developed my [Go wrapper](/fuzxxl/freefare). These issues can be found in the file [BUGS](/fuzxxl/freefare/blob/master/BUGS), the content of which is replicated below. I do not know how many of these issues are still open as the old bug tracker is no longer available.

    Bugs in the libfreefare that affect this project.
    
    mifare_ultralight.c
    
     * function mifare_ultralightc_authenticate does not set errno on encryption
       failure. This could make finding what kind of error happened a little bit
       more difficult. Anyway, cgo clears errno before any C call so this should not
       affect us in most circumstances. (Reported as issue #20, fixed)
    
    mifare_desfire_key.c
    
    * Objects of type MifareDESFireKey are opaque and allocated by the libfreefare.
      This makes it more difficult than it could be to wrap the library. These
      objects are not tied to any ressources and should therefore be treatable like
      any other "disposable" object. But because Go cannot track their allocation,
      the user of the Go wrapper has to manually keep track of MifareDESFireKeys.
      This is a huge inconvenience which could be entirely avoided by adding a
      callback to the libfreefare that allows a user to provide its own allocation
      function. (Reported as issue #21)
    
    mifare_classic.c
    
    * Some functions that assume a MifareTag is a Mifare Classic Tag don't check if
      that assumption holds. The wrapper has to perform extra checks to avoid memory
      corruption from invalid input data. (Reported as issue #23)
    
    mifare_application.c
    
    * The function mifare_application_free does not check for the possibility that
      mifare_application_find returned a NULL pointer. The libfreefare crashes when
      you try to delete a nonexisting application or when malloc returned NULL in
      mifare_application_find (Reported as issue #24 with patch). A similar issue
      exists with mifare_application_write. Even though the function checks the
      return valueo of mifare_application_find, it does not check if the NULL result
      came from malloc-failure and unconditionally returns EBADF instead of ENOMEM.
      (Reported as additional patch to issue #23)
    
    mifare_desfire.c
    
    * The function mifare_desfire_get_file_ids() has an argument files of type
      uint8_t *files[] (array of pointers to uint8_t). This should probably have
      been uint8_t (*files)[] (pointer to array of uint8_t). The same issue appears
      in mifare_desfire_get_iso_file_ids(): parameter uint16_t *files[] should have
      type uint16_t (*files)[]. (filed as issue #26)
    
    * The function mifare_desfire_read_data() writes more than length bytes into the
      data buffer. This is undocumented and I was unable to deduct how long the
      buffer is supposed to be. (filed as issue #28)
    
    freefare.c
    
    * The function freefare_get_tag_uid() does not check the return value of
      malloc, potentially causing crashes or memory corruption. (filed as issue #25,
      fixed)

**Comment by smortex** [comment]
The migration from Google Code to Github migrated the issues, however the submitter address is mangled by the process so issuer are not notified of changes :disappointed:.

After reviewing your list:
* #21 is being worked on ATM;
* #28 has been assigned to myself and planned for 1.0.0;
* All other issues are marked as closed.

Thanks!
