### ISSUE TITLE
Add safety check if length == 0

### ISSUE THREAD

**Issue by der-stefan** [nfc-tools/libfreefare#69]
https://github.com/nfc-tools/libfreefare/blob/69bf99b33daf350d23aee8abffa96b4ed96151d1/libfreefare/mifare_desfire_crypto.c#L70

We should add right after that:
```
if(len == 0) {
   return;
}
```
Else there occurs a segfault when reading `data[0]` and `data[-1]`. This happens, if a card isn't read correctly.

Same issue for function `lsl` and `xor` in the same file.

**Comment by SloCompTech** [comment]
I agree, it needs to be handled in one way, but it is not needed in xor, because there is no len - 1

**Comment by smortex** [comment]
:+1: May one of your create a Pull-Request please?

**Comment by smortex** [comment]
Maybe with unit-test?  Our unit tests are more integration tests than anything else, so maybe it's okay do to small tests too :wink:
